test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) ... test_CutDebt (HRX.Test.chatbot_ttest_model.chatBotModel) ... ok
test_IDClassifier (HRX.Test.chatbot_ttest_model.chatBotModel) ... ok
test_IfKnowDebtor (HRX.Test.chatbot_ttest_model.chatBotModel) ... ok
test_Installment (HRX.Test.chatbot_ttest_model.chatBotModel) ... ok
test_WillingToPay (HRX.Test.chatbot_ttest_model.chatBotModel) ... ok

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=72)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:你个骗子

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=112)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 107 : debtor_answer:你先说你是哪个

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=142)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 1 : debtor_answer:你管我是不是, 方案给我发到微信嘛, 这个是我朋友用我的身份证办的，和我没有关系。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=148)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 1 : debtor_answer:你管求得我的。能不能换个长点儿的还款周期呢,这个是我朋友用我的身份证办的，和我没有关系。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=155)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:你问我，我问谁呢

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=218)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:别再打来了

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=219)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:别有事没事打电话

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=220)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:别来烦我！！

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=221)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:别老打电话了

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=246)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 104 : debtor_answer:后天

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=247)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 104 : debtor_answer:后年再说

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=250)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 1 : debtor_answer:和我没关系，朋友借的

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=423)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 1 : debtor_answer:我不知道

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=665)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 1 : debtor_answer:我的身份证办的

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=705)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:我说真的，很讨厌这问题

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=737)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:我难得管

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=762)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:挂了别再打了

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=776)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 1 : debtor_answer:是不是和你有关系吗, 还有没有更低的方案, 不欠钱。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=785)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 104 : debtor_answer:最后警告一次不要打了, 等我出差回来再说。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=849)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 104 : debtor_answer:没时间

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=915)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:瓜娃娃

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=967)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:给老子滚，别再打来了

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=968)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 0 != 109 : debtor_answer:缺钱花你去问银行要，找我干嘛

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1169)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:不对啊

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1182)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:不晓得

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1188)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:不知

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1191)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:不知道呢

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1202)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:什么公司？没说过

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1240)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:你傻逼

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1254)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:你怕是在忽悠我哟

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1288)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:你把证据给我看

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1315)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:你有证据吗？

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1343)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:你问问隔壁的老王，估计是他搞的飞机。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1353)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:再打就报警了

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1355)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:再骚扰我，我就报警了

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1370)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:可不可以滚远点，听到你们这些鬼话就鬼火冒

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1397)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:啥子都没得

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1401)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:啥子？骗子走开

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1404)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:啥？骗子死开

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1420)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:怎么老打我电话

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1426)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:想不起来了呢

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1427)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:想套我信息？

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1455)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:我不清楚我要跟他本人核实

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1459)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:我不知道你在想什么

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1460)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 103 : debtor_answer:我不知道你在说什么

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1608)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:我认不到你，莫跟我说乃些

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1652)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:根本就是无理取闹

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1682)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:滚远点，别骚扰我

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1686)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:滚，胎神

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1690)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:爬远点，别骚扰我

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1691)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:爬远点，豁我嗦

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1692)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:现在骗子这么多，你以为我会相信你吗？

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1693)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:真晦气，今天第几个诈骗电话了。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1697)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:瞎扯淡

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1699)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:神叨叨的

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1722)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 0 : debtor_answer:还有这事？我都忘记了。

======================================================================
FAIL: test_ConfirmLoan (HRX.Test.chatbot_ttest_model.chatBotModel) (index=1760)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ozintel/Downloads/Tsl_python_progect/local_ml/Chatbot_project/Chatbot1.0/HRX/Test/chatbot_ttest_model.py", line 78, in test_ConfirmLoan
    self.assertEqual(each[1], self.model_ConfirmLoan.classify(each[2])['label'],msg='debtor_answer:'+each[2])
AssertionError: 1 != 109 : debtor_answer:骗子走开

----------------------------------------------------------------------
Ran 6 tests in 5.806s

FAILED (failures=57)
